#include "backends/graphics_api.h"

DEFINE_CONTIG_ARRAY_HEADERS(PointLight, POINT_LIGHT_SLOTS)
DEFINE_CONTIG_ARRAY_HEADERS(DirectionalLight, DIRECTIONAL_LIGHT_SLOTS)
DEFINE_CONTIG_ARRAY_HEADERS(SpotLight, SPOT_LIGHT_SLOTS)
